// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRCe1GpFq26iu179TXO0sNalE5eAvDvo8',
    appId: '1:417478724994:web:c119dcd4ec38eaca09d39b',
    messagingSenderId: '417478724994',
    projectId: 'focusquest-d328c',
    authDomain: 'focusquest-d328c.firebaseapp.com',
    storageBucket: 'focusquest-d328c.firebasestorage.app',
    measurementId: 'G-GCJ8MSD63J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAraRtfeMqsKTxcIt46_Ynj9koa2pqd3_A',
    appId: '1:417478724994:android:735b25feaeb446e309d39b',
    messagingSenderId: '417478724994',
    projectId: 'focusquest-d328c',
    storageBucket: 'focusquest-d328c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlC8XQVc7tSlJFjRJDXa73mFTrow43YZE',
    appId: '1:417478724994:ios:6c50bc28f58d0c3609d39b',
    messagingSenderId: '417478724994',
    projectId: 'focusquest-d328c',
    storageBucket: 'focusquest-d328c.firebasestorage.app',
    iosClientId: '417478724994-coe9dt66sgshed76t3bhanhq0mjecrcj.apps.googleusercontent.com',
    iosBundleId: 'me.rahulrajsb.focus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlC8XQVc7tSlJFjRJDXa73mFTrow43YZE',
    appId: '1:417478724994:ios:6c50bc28f58d0c3609d39b',
    messagingSenderId: '417478724994',
    projectId: 'focusquest-d328c',
    storageBucket: 'focusquest-d328c.firebasestorage.app',
    iosClientId: '417478724994-coe9dt66sgshed76t3bhanhq0mjecrcj.apps.googleusercontent.com',
    iosBundleId: 'me.rahulrajsb.focus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRCe1GpFq26iu179TXO0sNalE5eAvDvo8',
    appId: '1:417478724994:web:6678c2e0e84066e409d39b',
    messagingSenderId: '417478724994',
    projectId: 'focusquest-d328c',
    authDomain: 'focusquest-d328c.firebaseapp.com',
    storageBucket: 'focusquest-d328c.firebasestorage.app',
    measurementId: 'G-PJ3WW0VNNK',
  );
}
